### ISSUE TITLE
Index EAP

### ISSUE THREAD

**Issue by shuni95** [shuni95/SFCourse#13]
@TakeshiSW12 la vista de EAP debe indicar la institucion.

**Comment by shuni95** [comment]
@FarroTakeshi te odio :v

**Comment by FarroTakeshi** [comment]
Ya lo sabía pero esta vez por qué? :v

**Comment by shuni95** [comment]
@FarroTakeshi tengo la sospecha que nunca se resolvió el issue... por eso >:v
